=== nasa/OpenSPIFe/gov.nasa.ensemble.core.jscience/data-test/csvxml/schema/lass_import_format.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Proposed Schema for LASS file imports, S. Hillenius -->
<!-- Made changes to add timeFormat,instance interpolation, and default values as options-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="resources">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="columns"/>
        <xs:element ref="data"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="columns">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="column"/>
      </xs:sequence>
      <xs:attribute name="timeFormat" use="required" form="unqualified">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ISO8601">
              <xs:annotation>
            	<xs:documentation>
Absolute date/time format defined by the ISO-8601 standard, e.g.
  2011-04-15T12:34:56Z 
Reference:  http://www.w3.org/TR/xmlschema-2/#isoformats

Timezone should be written as "Z" and must be read as UTC if absent.  Milliseconds optional.
           		 </xs:documentation>
            	</xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="STK">
           	 <xs:annotation>
            	<xs:documentation>
"STK" format is defined to mean "d MMM yyyy H:mm:ss.SSS".

   Rationale:  Of the formats STK offers according to http://www.stk.com/resources/help/online/stk/source/stk/sc-03.htm, this is the one we understand has been selected by LADEE FDS.

The timezone shall never be explicitly specified and shall always implicitly be UTC.

   Rationale:  Engineering judgment.
           		 </xs:documentation>
            	</xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="column">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element ref="property" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="description" use="optional" type="xs:string"/>
      <xs:attribute name="displayName" use="optional" type="xs:string"/>
      <xs:attribute name="interpolation" use="required" form="unqualified">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="step"/>
            <xs:enumeration value="linear"/>
            <xs:enumeration value="instantaneous"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="defaultValue" use="optional" type="xs:string"/>
      <xs:attribute name="id" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_]+"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Integer"/>
            <xs:enumeration value="Double"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="String"/>
            <xs:enumeration value="Date"/>
          </xs:restriction>
        </xs:simpleType>        
      </xs:attribute>
      <xs:attribute name="units" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="property">
    <xs:complexType mixed="false">
      <xs:attribute name="key" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="data" type="xs:string"/>
</xs:schema>

=== nasa/OpenSPIFe/gov.nasa.ensemble.core.jscience/data-test/csvxml/inputs/incorrect-csv-number.xml
<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../schema/lass_import_format.xsd">
    <!-- In this one, the CSV is malformed (but the XML is valid).
         This supports two tests:
         1.  That the expected exception is thrown when we attempt to get the datapoints.
         2.  That the error only occurs when we try to get the datapoints;
             the other info is accessible without triggering an error.
             This demonstrates that the other info is accessible without reading the whole file,
             which is a desirable feature for performance reasons.
              -->
   <columns timeFormat="ISO8601">
        <column id="RN1" units="W" type="Double" description="test unit description"
            interpolation="step" displayName="Resource Name 1">
            <property key="LADEE Subsystem Metadata" value="Test metadata"/>
        </column>
        <column id="RN2" type="Boolean" description="test description" interpolation="instantaneous"
            displayName="Resource Name 2" defaultValue="false">
            <property key="LADEE Subsystem Metadata" value="Test metadata"/>
        </column>
        <column id="RN3" type="String" description="test description" interpolation="step"
            displayName="Resource Name 3">
            <property key="LADEE Subsystem Metadata" value="Test metadata"/>
        </column>
    </columns>
    <data>
        <![CDATA[
    StartTime,RN1,RN2,RN3
    2011-02-03T16:27:00Z,50,true,Moon
    2011-02-03T16:28:00Z,63W,questionable,Vulcan
    2011-02-03T16:29:00Z;foo
    2011-02-03T16.29-00Z;foo
     ]]>
    </data>
</resources>

=== nasa/OpenSPIFe/gov.nasa.ensemble.core.jscience/data-test/csvxml/inputs/leave-out-CDATA--values-match-iso8601-dates.xml
<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../schema/lass_import_format.xsd">
    <!-- In this one, the data values match some field of the timestamp in UTC.
    Tests date, string, and integer parsing. -->
    <columns timeFormat="ISO8601">
         <column id="MMMM" description="month" type="String" interpolation="instantaneous"/>
         <column id="d" description="day" type="Integer" interpolation="instantaneous"/>
         <column id="yyyy" description="year" type="Integer" interpolation="instantaneous"/>
         <column id="H" description="hour" type="Integer" interpolation="instantaneous"/>
         <column id="m" description="minute" type="Integer" interpolation="instantaneous"/>
         <column id="s" description="second" type="Integer" interpolation="instantaneous"/>
    </columns>
    <data>
    StartTime,MMMM, d, yyyy, H,m,s
    2011-04-06T00:00:10Z,April,6, 2011, 0,0,10
    2011-04-15T12:34:56Z,April,15, 2011,   12,34,56
    2011-05-01T12:34:56Z, May,1, 2011,   12,34,56
     </data>
</resources>

=== nasa/OpenSPIFe/gov.nasa.ensemble.core.jscience/data-test/csvxml/inputs/interpolation.xml
<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../schema/lass_import_format.xsd">
    <!-- In this one, the first, second, and third data values at each date
    	 whether specified explicitly or interpolated, are equal to the
    	 fourth, fifth, and sixth value respectively on the same date row.
    	 
    	 Thus, this tests all interpolation types.   -->
    <columns timeFormat="ISO8601">
         <column id="step" type="Double" interpolation="step">
         	<property key="interpolate_at_date" value="2011-04-01T09:00:00Z"/>
         	<property key="expected_interpolated_value" value="500"/>
         </column>
         <column id="instantaneous" type="Double" interpolation="instantaneous" defaultValue="777">
         	<property key="interpolate_at_date" value="2011-04-01T09:00:00Z"/>
          	<property key="expected_interpolated_value" value="777"/>
         </column>
         <column id="linear" type="Double" interpolation="linear">
         	<property key="interpolate_at_date" value="2011-04-01T09:00:00Z"/>
          	<property key="expected_interpolated_value" value="590"/>
         </column>
         <column id="Cf1" type="Double" interpolation="instantaneous"/>
         <column id="Cf2" type="Double" interpolation="instantaneous"/>
         <column id="Cf3" type="Double" interpolation="instantaneous"/>
    </columns>
    <data>
        <![CDATA[
StartTime,    step,instantaneous,linear,    Cf1, Cf2, Cf3
    2011-04-01T00:00:00Z, 500, 500, 500,    500, 500, 500
    2011-04-01T20:00:00Z, 700, 700, 700,    700, 700, 700
    2011-04-06T00:00:11Z, 123,    , 789,    123, 777, 789
    2011-04-06T00:00:12Z,    , 150, 111,    123, 150, 111
    2011-04-06T00:00:13Z, 500, 400, 300,    500, 400, 300
    2011-04-06T00:00:14Z,    ,    ,    ,    500, 777, 250 
    2011-04-06T00:00:15Z, 555, 222, 200,    555, 222, 200
     ]]>
    </data>
</resources>

=== nasa/OpenSPIFe/gov.nasa.ensemble.core.jscience/data-test/csvxml/expected-outputs/sparse.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/lass_import_format.xsd">
  <columns timeFormat="ISO8601">
    <column id="col_1" interpolation="step" type="Integer"/>
    <column id="col_2" interpolation="step" type="Integer"/>
    <column id="col_3" interpolation="step" type="Integer"/>
    <column id="col_4" interpolation="step" type="Integer"/>
    <column id="col_5" interpolation="step" type="Integer"/>
    <column id="col_6" interpolation="step" type="Integer"/>
    <column id="col_7" interpolation="step" type="Integer"/>
    <column id="col_8" interpolation="step" type="Integer"/>
    <column id="col_9" interpolation="step" type="Integer"/>
    <column id="col_10" interpolation="step" type="Integer"/>
    <column id="col_11" interpolation="step" type="Integer"/>
    <column id="col_12" interpolation="step" type="Integer"/>
    <column id="col_13" interpolation="step" type="Integer"/>
    <column id="col_14" interpolation="step" type="Integer"/>
    <column id="col_15" interpolation="step" type="Integer"/>
    <column id="col_16" interpolation="step" type="Integer"/>
    <column id="col_17" interpolation="step" type="Integer"/>
    <column id="col_18" interpolation="step" type="Integer"/>
    <column id="col_19" interpolation="step" type="Integer"/>
    <column id="col_20" interpolation="step" type="Integer"/>
    <column id="col_21" interpolation="step" type="Integer"/>
    <column id="col_22" interpolation="step" type="Integer"/>
    <column id="col_23" interpolation="step" type="Integer"/>
    <column id="col_24" interpolation="step" type="Integer"/>
    <column id="col_25" interpolation="step" type="Integer"/>
    <column id="col_26" interpolation="step" type="Integer"/>
    <column id="col_27" interpolation="step" type="Integer"/>
    <column id="col_28" interpolation="step" type="Integer"/>
    <column id="col_29" interpolation="step" type="Integer"/>
    <column id="col_30" interpolation="step" type="Integer"/>
  </columns>
  <data><![CDATA[
Time,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12,col_13,col_14,col_15,col_16,col_17,col_18,col_19,col_20,col_21,col_22,col_23,col_24,col_25,col_26,col_27,col_28,col_29,col_30
2011-04-03T07:00:00Z,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2011-04-10T07:00:00Z,,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2011-04-17T07:00:00Z,,,3,,,,,,,,,,,,,,,,,,,,,,,,,,,
2011-04-24T07:00:00Z,,,,4,,,,,,,,,,,,,,,,,,,,,,,,,,
2011-05-01T07:00:00Z,,,,,5,,,,,,,,,,,,,,,,,,,,,,,,,
2011-05-08T07:00:00Z,,,,,,6,,,,,,,,,,,,,,,,,,,,,,,,
2011-05-15T07:00:00Z,,,,,,,7,,,,,,,,,,,,,,,,,,,,,,,
2011-05-22T07:00:00Z,,,,,,,,8,,,,,,,,,,,,,,,,,,,,,,
2011-05-29T07:00:00Z,,,,,,,,,9,,,,,,,,,,,,,,,,,,,,,
2011-06-05T07:00:00Z,,,,,,,,,,10,,,,,,,,,,,,,,,,,,,,
2011-06-12T07:00:00Z,,,,,,,,,,,11,,,,,,,,,,,,,,,,,,,
2011-06-19T07:00:00Z,,,,,,,,,,,,12,,,,,,,,,,,,,,,,,,
2011-06-26T07:00:00Z,,,,,,,,,,,,,13,,,,,,,,,,,,,,,,,
2011-07-03T07:00:00Z,,,,,,,,,,,,,,14,,,,,,,,,,,,,,,,
2011-07-10T07:00:00Z,,,,,,,,,,,,,,,15,,,,,,,,,,,,,,,
2011-07-17T07:00:00Z,,,,,,,,,,,,,,,,16,,,,,,,,,,,,,,
2011-07-24T07:00:00Z,,,,,,,,,,,,,,,,,17,,,,,,,,,,,,,
2011-07-31T07:00:00Z,,,,,,,,,,,,,,,,,,18,,,,,,,,,,,,
2011-08-07T07:00:00Z,,,,,,,,,,,,,,,,,,,19,,,,,,,,,,,
2011-08-14T07:00:00Z,,,,,,,,,,,,,,,,,,,,20,,,,,,,,,,
2011-08-21T07:00:00Z,,,,,,,,,,,,,,,,,,,,,21,,,,,,,,,
2011-08-28T07:00:00Z,,,,,,,,,,,,,,,,,,,,,,22,,,,,,,,
2011-09-04T07:00:00Z,,,,,,,,,,,,,,,,,,,,,,,23,,,,,,,
2011-09-11T07:00:00Z,,,,,,,,,,,,,,,,,,,,,,,,24,,,,,,
2011-09-18T07:00:00Z,,,,,,,,,,,,,,,,,,,,,,,,,25,,,,,
2011-09-25T07:00:00Z,,,,,,,,,,,,,,,,,,,,,,,,,,26,,,,
2011-10-02T07:00:00Z,,,,,,,,,,,,,,,,,,,,,,,,,,,27,,,
2011-10-09T07:00:00Z,,,,,,,,,,,,,,,,,,,,,,,,,,,,28,,
2011-10-16T07:00:00Z,,,,,,,,,,,,,,,,,,,,,,,,,,,,,29,
2011-10-23T07:00:00Z,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,30
]]></data>
</resources>

=== nasa/OpenSPIFe/gov.nasa.ensemble.core.jscience/data-test/csvxml/expected-outputs/simple.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/lass_import_format.xsd">
  <columns timeFormat="ISO8601">
    <column displayName="Profile Name 1" id="P1" interpolation="linear" type="Double" units="W">
      <property key="flavor" value="cherry"/>
      <property key="color" value="red"/>
    </column>
    <column defaultValue="true" id="P2" interpolation="instantaneous" type="Boolean">
      <property key="flavor" value="spearmint"/>
      <property key="color" value="green"/>
    </column>
    <column displayName="Profile Name 3" id="P3" interpolation="step" type="String"/>
  </columns>
  <data><![CDATA[
Time,P1,P2,P3
]]></data>
</resources>

=== nasa/OpenSPIFe/gov.nasa.ensemble.core.jscience/data-test/csvxml/inputs/values-match-stk-dates.xml
<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../schema/lass_import_format.xsd">
    <!-- In this one, the data values match some field of the timestamp in UTC.
    Tests date, string, and integer parsing. -->
    <columns timeFormat="STK">
         <column id="MMMM" description="month" type="String" interpolation="instantaneous"/>
         <column id="d" description="day" type="Integer" interpolation="instantaneous"/>
         <column id="yyyy" description="year" type="Integer" interpolation="instantaneous"/>
         <column id="H" description="hour" type="Integer" interpolation="instantaneous"/>
         <column id="m" description="minute" type="Integer" interpolation="instantaneous"/>
         <column id="s" description="second" type="Integer" interpolation="instantaneous"/>
         <column id="SSS" description="millisecond" type="Integer" interpolation="instantaneous"/>
    </columns>
    <data>
        <![CDATA[
               StartTime,MMMM, d, yyyy, H,m,s,SSS
    9 Apr 2011 00:00:10.000,April,9, 2011, 0,0,10, 0
    15 Apr 2011 12:34:56.789,April,15, 2011,   12,34,56, 789
    1 May 2011 13:00:00.001, May,1, 2011,   13,00,00, 1
    ]]>
    </data>
</resources>

=== nasa/OpenSPIFe/gov.nasa.ensemble.core.jscience/data-test/csvxml/inputs/nominal-example.xml
<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../schema/lass_import_format.xsd">
    <!-- Standard XML Comments -->
    <columns timeFormat="ISO8601">
        <column id="RN1" units="W" type="Double" description="test unit description"
            interpolation="linear" displayName="Resource Name 1">
            <property key="metadata test" value="one"/>
            <property key="color" value="red"/>
            <property key="flavor" value="strawberry"/>
         </column>
        <column id="RN2" type="Boolean" description="test description" interpolation="instantaneous"
            displayName="Resource Name 2" defaultValue="false">
            <property key="color" value="blue"/>
            <property key="flavor" value="blueberry"/>
            <property key="metadata test" value="two"/>
        </column>
        <column id="RN3" type="String" description="test description" interpolation="step"
            displayName="Resource Name 3">
            <property key="metadata test" value="three"/>
        </column>
    </columns>
    <data>
        <![CDATA[
    StartTime,RN1,RN2,RN3
    2011-02-03T16:27:00.000Z,50,true,Moon
    2011-02-03T16:28:00Z,63,true,Earth
    2011-02-03T16:29:00Z,63,,Earth
    ]]>
    </data>
</resources>
